### ISSUE TITLE
Error viewing profile

### ISSUE THREAD

**Issue by aroller** [usplm/UsplmPortal-Beta#1]
When viewing my Profile I get an error message:

https://dfom.usplm.net:9000/user/profile/894D95DA5569482CA3EBEBE74426E854

*Steps*
1. Login as `Aaron Roller`
1. Click on name
1. Click on Profile

*Expected*
* View profile

*Actual*
* Error viewing profile.  See 

![image](https://user-images.githubusercontent.com/312949/68424504-0375f280-0159-11ea-83bf-7aa0563ab6ff.png)

**Comment by usplm** [comment]
Aaron, it has been reproduced and fixed.
